spring:
  application:
    name: WeatherApplication
  datasource:
    url: jdbc:postgresql://localhost:5432/sensor
    username: user
    password: user
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update # todo liquibase
    show-sql: true
    properties:
      hibernate:
        format_sql: true

---

spring:
  config:
    activate:
      on-profile: it